name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Install dependencies
      run: |
        uv sync --dev
        uv add --dev black isort flake8 mypy
    
    - name: Check code formatting with Black
      run: uv run black --check --diff src/ tests/
    
    - name: Check import sorting with isort
      run: uv run isort --check --diff src/ tests/
    
    - name: Run flake8
      run: uv run flake8 src/ tests/ --max-line-length=88 --extend-ignore=E203,W503
    
    - name: Run mypy
      run: uv run mypy src/ --ignore-missing-imports